[build]
target = "riscv32imafc-unknown-none-elf"

[target.riscv32imafc-unknown-none-elf]
rustflags = [
    "-C", "link-arg=-Map=kernel.map",
    "--cfg", "portable_atomic_unsafe_assume_single_core",
]
runner = "./openocd-runner.sh"

[unstable]
build-std = ["core"]
