[build]
target = "riscv32emc-unknown-none-elf"

[target.riscv32emc-unknown-none-elf]
rustflags = [
    "-C", "link-arg=-Tlinker.ld",
    "-C", "link-arg=-Map=kernel.map",
]
runner = "./openocd-runner.sh"

[unstable]
build-std = ["core"]
